pr:
  branches:
    include:
      - master
  paths:
    include:
      - .stress.yml
      - .azure-pipelines-templates/*

trigger: none

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: Stress test build
  branches:
    include:
    - master
  always: true

resources:
  containers:
    - container: sgx
      image: ccfciteam/ccf-ci:vegeta
      options: --publish-all --device /dev/sgx:/dev/sgx -v /dev/shm:/tmp/ccache

jobs:
- template: .azure-pipelines-templates/stress-matrix.yml 
