parameters:
  env:
    NoSGX:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
    SGX:
      container: sgx
      pool: Ubuntu-1804-DC8_v2

  build:
    NoSGX:
      cmake_args: '-DCOMPILE_TARGETS=virtual'
    SGX:
      cmake_args: '-DCOMPILE_TARGETS=sgx'
    debug:
      cmake_args: '-DCMAKE_BUILD_TYPE=Debug -DSAN=ON -DCOVERAGE=ON -DBUILD_SMALLBANK=OFF -DLVI_MITIGATIONS=OFF'

jobs:
  - job: 'Make'
    displayName: 'Make generator'
    ${{ insert }}: '${{ parameters.env.NoSGX }}'
    variables:
      skipComponentGovernanceDetection: true
    steps:
      - checkout: self
        clean: true
      - script: |
          mkdir build_make
          cd build_make
          cmake -L .. ${{ parameters.build.NoSGX.cmake_args }}
        displayName: CMake

  - template: common.yml
    parameters:
      target: NoSGX
      env: '${{ parameters.env.NoSGX }}'
      cmake_args: '${{ parameters.build.debug.cmake_args }} ${{ parameters.build.NoSGX.cmake_args }}'
      suffix: 'Instrumented'
      artifact_name: 'NoSGX_Instrumented'
      ctest_filter: '-LE "benchmark|perf"'
      ctest_timeout: '300'

  - template: common.yml
    parameters:
      target: SGX
      env: '${{ parameters.env.SGX }}'
      cmake_args: '${{ parameters.build.SGX.cmake_args }} -DTLS_TEST=ON -DSHUFFLE_SUITE=ON'
      suffix: 'Release'
      artifact_name: 'SGX_Release'
      ctest_filter: '-LE "benchmark|perf"'
