jobs:
  - template: common.yml
    parameters:
      target: SGX
      env:
        container: sgx
        pool: Ubuntu-1804-DC8_v2
      cmake_args: '-DCOMPILE_TARGETS=sgx'
      suffix: 'StressTest'
      artifact_name: 'NoSGX_Instrumented'
      ctest_filter: '-L "vegeta" -C "long_stress"'
      ctest_timeout: '0' # No timeout
